import { Aclonica, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const aclonica = Aclonica({
  variable: "--font-aclonica",
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Dulsie Kys Cooking",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${aclonica.variable} antialiased`}
      > 
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
